# Generated by ChatGPT prompt
# "Write a python script to listen for a rasberry pi to listen for a button push and trigger a relay for 10 seconds if pushed"
# "Update this code so it also triggers the relay from the hours of 6am to 11am"

import RPi.GPIO as GPIO
import time
from datetime import datetime

# Set up GPIO
GPIO.setmode(GPIO.BCM)

# Define GPIO pins
BUTTON_PIN = 17  # Change this to the actual GPIO pin you've connected the button to
RELAY_PIN = 18   # Change this to the actual GPIO pin you've connected the relay to

# Set up GPIO for button as input
GPIO.setup(BUTTON_PIN, GPIO.IN, pull_up_down=GPIO.PUD_UP)

# Set up GPIO for relay as output
GPIO.setup(RELAY_PIN, GPIO.OUT)
GPIO.output(RELAY_PIN, GPIO.LOW)  # Turn off the relay initially

def trigger_relay():
    GPIO.output(RELAY_PIN, GPIO.HIGH)  # Turn on the relay
    time.sleep(10)  # Keep the relay on for 10 seconds
    GPIO.output(RELAY_PIN, GPIO.LOW)   # Turn off the relay

def is_time_between(start_time, end_time, current_time):
    return start_time <= current_time <= end_time

try:
    print("Press the button to trigger the relay or relay will be triggered from 6am to 11am...")

    while True:
        now = datetime.now().time()
        if is_time_between(time(6, 0), time(11, 0), now):
            print(f"Current time is {now}, triggering relay...")
            trigger_relay()

        input_state = GPIO.input(BUTTON_PIN)
        if input_state == False:
            print("Button pressed!")
            trigger_relay()

except KeyboardInterrupt:
    GPIO.cleanup()
